version: '3'
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: catalogo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  web:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/catalogo
    ports:
      - "5000:5000"
